### ISSUE TITLE
Sh files should be committed executable

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix-systemlock#19]
Please remove these lines from the travis build and commit the executable files:
https://travis-ci.org/fossasia/meilix-systemlock/builds/234687851#L122

**Comment by meets2tarun** [comment]
If we remove the line, then it will not be executable.
chmod +x gives the permission to the file to be executable

**Comment by niccokunzmann** [comment]
Correct. But they should be executable after cloning the repository. Git allows committing files with the executable flag.

**Comment by meets2tarun** [comment]
So if we remove that line from the Travis build then it will still be executable.

**Comment by niccokunzmann** [comment]
Yes.

**Comment by meets2tarun** [comment]
Thanks you
Please close this
