### ISSUE TITLE
Debuild

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-systemlock#22]
- Issue type: Feature request 

### Short description

Add a debuild Travis integration analogue how it is done in Meilix-artwork so that debs are created via CI.

**Comment by pranav1698** [comment]
I am claiming this issue, I will add the required scripts and the required files as done in meilix-artwork repo in subsquent issues and pr's
Then we can make changes in the meilix main repo

**Comment by pranav1698** [comment]
@tabesin This can be closed now
