### ISSUE TITLE
Fix Lintian issue wrong bug number in closes 

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-systemlock#32]
- Issue type: Bug report 

### Short description

Lintian reports:
`W: systemlock: wrong-bug-number-in-closes l3:#nnnn`

### Environment

 - Operating system: Ubunutu 18.04, travis
 - Software version: 
 - Software source: 

### Steps to reproduce

In the current build;
1. cd into the systemlock-0.1 folder
2. run debuild -uc -us
3. Their will be lintian warnings
Note: In the current build you will get errors; that are solved in pr #26; but for now you can solve it

### Description

See section 4.4. of the Debian Policy manual.
https://www.debian.org/doc/debian-policy/ch-source.html#debian-changelog-debian-changelog

**Comment by Manas-kashyap** [comment]
I am working on it
