### ISSUE TITLE
Automatic starting of travis check

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-systemlock#6]
Although there is no .travis.yml file, then how Travis CI check starts automatically.

**Comment by xeon-zolt** [comment]
i have included one in #3

**Comment by meets2tarun** [comment]
Exactly if the pr is not merged then how can it show its effect?

**Comment by xeon-zolt** [comment]
mine was tested with the .yml file i included and yours was tested without it

**Comment by meets2tarun** [comment]
Travis test also happened with the PR that I made.

**Comment by Abhi2424shek** [comment]
If there is no .yml file, Travis tries to detect what language the program is in, if it can't it will execute the commands assuming the program is programmed in ruby, if you enabled Travis to run on the repository

**Comment by meets2tarun** [comment]
I get that but Travis PR hasn't been merged yet.
Then how it get effective in other persons' PR.

**Comment by Abhi2424shek** [comment]
What do you mean by Travis PR?

**Comment by meets2tarun** [comment]
(commit)[https://github.com/fossasia/meilix-systemlock/pull/3/commits/d499d06fb3c26787906de4446766d90d47861c2f] consists in PR.

**Comment by Abhi2424shek** [comment]
It will work only after being merged.

**Comment by meets2tarun** [comment]
But it also checks my PR before being merged

**Comment by Abhi2424shek** [comment]
As I stated before, Travis has been enabled for here, and that's why it's happening. You may ignore Travis till the time it's working and a successfull build has been made. :)
